# try-catch combinator example
packages:
  plugin-combinator-1:
    actions:
      safeToDelete:
        kind: nodejs
        code: |
          if (params.delete)
            return {}
          throw new Error('Oh Crap')

      delete:
        kind: nodejs
        code: |
          delete params[params.delete]
          return params

      handleError:
        kind: nodejs
        code: |
          return {status: 'Um a very bad thing just happened - sorry?'}

      trycatch:
        combinator: try safeToDelete catch handleError

      eca:
        combinator: if safeToDelete then delete

      forward:
        combinator: forward ["authkey"] after safeToDelete with ["delete"]
        inputs:
          authkey: very private
          delete: something

      retry:
        combinator: retry delete 5 times
